# Generated by Django 5.0.4 on 2024-05-31 01:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_checkout_estimated_arrival_anonymousorder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousorder',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anonymousorder',
            name='estimated_arrival',
            field=models.DateField(default=datetime.datetime(2024, 6, 14, 1, 13, 28, 15756, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='estimated_arrival',
            field=models.DateField(default=datetime.datetime(2024, 6, 14, 1, 13, 28, 14759, tzinfo=datetime.timezone.utc)),
        ),
    ]
