# Generated by Django 5.0.4 on 2024-05-30 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='estimated_arrival',
            field=models.DateField(default=datetime.datetime(2024, 6, 13, 0, 41, 45, 511923, tzinfo=datetime.timezone.utc)),
        ),
    ]
